### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by daxiangzi166** [FengLiuFeseliud/CloudMusic-Mod#1]
在播放歌曲的时候，有的歌曲无法正常播放，无论是vip歌曲还是免费歌曲

**Comment by FengLiuFeseliud** [comment]
能举例吗？

**Comment by daxiangzi166** [comment]
已经绑定cookie的情况下播放

https://user-images.githubusercontent.com/105540716/210044758-98de054e-2fd4-403e-84ae-faecdfb17e78.mp4
而且在同样的cookie的情况下，网易云web端可以使用

**Comment by FengLiuFeseliud** [comment]
查看日志输出，我这里配置文件 `play.url=false` 可以播放

![屏幕截图 2022-12-30 174703](https://user-images.githubusercontent.com/73475715/210056799-8faefe09-5f16-436b-bfa6-5460e8a0b376.png)

https://user-images.githubusercontent.com/73475715/210057889-9d68c385-60c7-479f-aa3a-fc0df62a7af3.mp4

**Comment by FengLiuFeseliud** [comment]
你是不是自己构建的 jar，缺少了依赖也播放不了，可以尝试我这的 jar https://modrinth.com/mod/cloudmusic/version/0.1.0
