### ISSUE TITLE
1.20.1 要求了不正确的 MaliLib 版本 0.17.x

### ISSUE THREAD

**Issue by TowardtheStars** [FengLiuFeseliud/CloudMusic-Mod#17]
0.17.x 的 MaliLib 仅兼容 1.20.2，不兼容 1.20.1，但 1.20.1 的 CloudMusic 要求使用 0.17.x 的 MaliLib，这使得本模组实际上在 1.20.1 不兼容

在 1.20.1 应使用 MaliLib 0.16.x

**Comment by FengLiuFeseliud** [comment]
使用这个版本 https://modrinth.com/mod/cloudmusic/version/0.4.5
