### ISSUE TITLE
建议右上角歌曲信息在有药水效果时向下偏移

### ISSUE THREAD

**Issue by hiruocha** [FengLiuFeseliud/CloudMusic-Mod#18]
类似MiniHUD的效果，如果把MiniHUD的信息放到右上角的话获得药水效果时会自动向下偏移，不偏移的话会被挡住
![微信图片_20240103101031](https://github.com/FengLiuFeseliud/CloudMusic-Mod/assets/86976382/465a8854-e1ff-42bb-8a32-cfb4007517ab)

**Comment by FengLiuFeseliud** [comment]
0.4.7 增加
