### ISSUE TITLE
[Small bug] 在Mod Menu内，mod 简介编码出错 / In Mod Menu, the character encoding is wrong

### ISSUE THREAD

**Issue by soloopooo** [FengLiuFeseliud/CloudMusic-Mod#3]
![图片](https://user-images.githubusercontent.com/36123081/210194035-a3bf84b1-7a0d-4755-b75c-2d661e0f77c5.png)

**Comment by soloopooo** [comment]
mod jar from modrinth

**Comment by FengLiuFeseliud** [comment]
v0.3.0 修复
