### ISSUE TITLE
[Optimization] 建议修改上一首（页面）/下一首（页面）的相关指令 / Please Consider Changing the command of Changing songs and pages

### ISSUE THREAD

**Issue by soloopooo** [FengLiuFeseliud/CloudMusic-Mod#4]
现在的指令切歌是 up down.
但现在这个指令是非常不符合语言习惯的，一般下一首歌是next，上一首歌是previous (prev).
所以请求更改为 next prev 切歌，更加符合语言习惯。

**Comment by soloopooo** [comment]
其实 切换页面（page）使用的也是next previous。请考虑一同修改，谢谢您。

**Comment by FengLiuFeseliud** [comment]
可以，在v0.3.2修改
