### ISSUE TITLE
Will the mod provide more versions below?

### ISSUE THREAD

**Issue by glowinXD** [FengLiuFeseliud/CloudMusic-Mod#5]
I want to use it in Minecraft 1.18.2, will there be a suitable plan?
我希望在 1.18.2 中使用，是否会有向下适配的计划？

**Comment by FengLiuFeseliud** [comment]
向下适配要改代码，我打算功能完善了再进行适配

**Comment by glowinXD** [comment]
> 向下适配要改代码，我打算功能完善了再进行适配

我知道了，谢谢啦qwq
