### ISSUE TITLE
歌词不同步

### ISSUE THREAD

**Issue by IF-desu** [FengLiuFeseliud/CloudMusic-Mod#8]
游戏版本1.18.2
mod版本0.4.2
尝试卸载了exordium后依旧

https://user-images.githubusercontent.com/86994398/219826359-146722cf-9481-49a0-81ab-cf8cc01d4ce8.mp4

**Comment by FengLiuFeseliud** [comment]
歌词问题, 单行歌词轴正常

**Comment by Apricityx** [comment]
1.20也出现了这种问题，八成以上的歌曲歌词都不同步
