### ISSUE TITLE
[BUG] 1.19.4版本使用0.15.4版本的malilib后无法从modmenu处进入配置文件

### ISSUE THREAD

**Issue by shinyashen** [FengLiuFeseliud/CloudMusic-Mod#9]
![image](https://user-images.githubusercontent.com/90324553/236746341-3f1c5700-dce8-45d0-b963-92e441d68cb5.png)
错误如上图所示，该问题在使用1.19.4最新版本的malilib(0.15.4)后出现，使用0.15.3的malilib则没有这个问题

**Comment by FengLiuFeseliud** [comment]
明天修

**Comment by FengLiuFeseliud** [comment]
已修复更新至 `v0.4.3.1`
